### ISSUE TITLE
no-duplicate-store-ids 这个有bug

### ISSUE THREAD

**Issue by pagnkelly** [lisilinhart/eslint-plugin-pinia#56]
只要你打开编辑器，然后关掉，再打开就会报错

**Comment by 9romise** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by pagnkelly** [comment]
I am unable to provide a minimal reproduction. In VSCode, every time a file is opened, the ESLint rule is executed. The first time the file is opened, this rule will add the ID to the set. The second time the same file is opened, an error will occur because the ID already exists in the set
